config/routes.rb
Rails.application.routes.draw do
  root to: 'nipis#index'
  resources :nipis, only: [:index, :new] do
    collection do
      get 'team_c'
      get 'cocktail_app'
      get 'mypet'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nipis_controller.rb
class NipisController < ApplicationController
  def team_c
  end

  def cocktail_app
  end

  def mypet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nipis_helper.rb
module NipisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NipiProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nipis/cocktail-app.html.erb
<div class='lottery-title'>
  <p>カクテルアプリ</p>
</div>

app/views/nipis/cocktail_app.html.erb
<%= render 'shared/header' %>
<div class='cocktail-title'>
  <p>カクテルアプリ</p>
</div>

<div class='cocktail-text'>
  <p>カクテルのレシピを見れるアプリ</p>
</div>

<ul class='cocktail-lists'>
  <p class='cocktail-list'>使った言語</p>
  <li>Java</li>
</ul>
<ul class='cocktail-lists'>
  <p class='cocktail-framework'>使ったフレームワーク</p>
  <li>spring boot</li>
</ul>
<div class='cocktail-btn'>
  <%= link_to 'リンク', 'https://cocktail-app10.herokuapp.com/', class:'cocktail-link' %>
</div>

<%= render 'shared/footer' %>

app/views/nipis/index.html.erb
<%= render 'shared/header' %>
<div class='header-title'>
  <span>Nipi</span><br>
  <span>Project</span>
</div>

<%= link_to team_c_nipis_path, class:'app-btn' do %>
  <div class='app-1-title'>
    <p>抽選アプリ</p>
  </div>
<% end %>

<%= link_to cocktail_app_nipis_path, class:'app-btn' do %>
  <div class='app-2-title'>
    <p>カクテルアプリ</p>
  </div>
<% end %>

<%= link_to mypet_nipis_path, class:'app-btn' do %>
  <div class='app-3-title'>
    <p>日記アプリ</p>
  </div>
<% end %>

<%= render 'shared/footer' %>

app/views/nipis/mypet.html.erb
<%= render 'shared/header' %>

<div class='mypet-title'>
  <p>日記アプリ</p>
</div>

<div class='lottery-text'>
  <p>ペットの日記をペットごとに保存するアプリ</p>
</div>

<ul class='lottery-lists'>
  <p class='lottery-list'>使った言語</p>
  <li>Python</li>
</ul>

<ul class='lottery-lists'>
  <p class='lottery-framework'>使ったフレームワーク</p>
  <li>Django</li>
</ul>

<div class='lottery-btn'>
  <%= link_to 'リンク', 'https://team-c-84.herokuapp.com/', class:'lottery-link' %>
</div>

<%= render 'shared/footer' %>

app/views/nipis/new.html.erb
<div class='lottery-title'>
  <p>抽選アプリ</p>
</div>

<div class='lottery-text'>
  <p>チェックをつけた人の中からランダムで1人を選ぶ抽選アプリ</p>
</div>

<ul class='lottery-language'>
  <p class='lottery-list'>使った言語</p>
  <li>Ruby</li>
  <li>jQuery</li>
</ul>

<%= link_to 'リンク', 'https://team-c-84.herokuapp.com/' %>

app/views/nipis/team-c.html.erb
<div class='lottery-title'>
  <p>抽選アプリ</p>
</div>

<div class='lottery-text'>
  <p>チェックをつけた人の中からランダムで1人を選ぶ抽選アプリ</p>
</div>

<ul class='lottery-language'>
  <p class='lottery-list'>使った言語</p>
  <li>Ruby</li>
  <li>jQuery</li>
</ul>

<%= link_to 'リンク', 'https://team-c-84.herokuapp.com/' %>

app/views/nipis/team_c.html.erb
<%= render 'shared/header' %>

<div class='lottery-title'>
  <p>抽選アプリ</p>
</div>

<div class='lottery-text'>
  <p>チェックをつけた人の中からランダムで1人を選ぶ抽選アプリ</p>
</div>

<ul class='lottery-lists'>
  <p class='lottery-list'>使った言語</p>
  <li>Ruby</li>
  <li>jQuery</li>
</ul>

<ul class='lottery-lists'>
  <p class='lottery-framework'>使ったフレームワーク</p>
  <li>Ruby on Rails</li>
</ul>

<div class='lottery-btn'>
  <%= link_to 'リンク', 'https://team-c-84.herokuapp.com/', class:'lottery-link' %>
</div>

<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<p class='footer-title-name'>Nipi Project</p>

app/views/shared/_header.html.erb
<p class='main-title'>Nipi Project</p>